-- Insertion des catégories
INSERT INTO category (id, name) VALUES (1, 'Electronics');
INSERT INTO category (id, name) VALUES (2, 'Clothing');
INSERT INTO category (id, name) VALUES (3, 'Home & Kitchen');
INSERT INTO category (id, name) VALUES (4, 'Books');
INSERT INTO category (id, name) VALUES (5, 'Sports & Outdoors');

-- Insertion des produits
INSERT INTO product (id, name, description, category_id) VALUES (1,'Product 1', 'Description for product 1, a high-quality item for everyday use.', 5);
INSERT INTO product (id, name, description, category_id) VALUES (2,'Product 2', 'Description for product 2, a high-quality item for everyday use.', 3);
INSERT INTO product (id, name, description, category_id) VALUES (3,'Product 3', 'Description for product 3, a high-quality item for everyday use.', 2);
INSERT INTO product (id, name, description, category_id) VALUES (4,'Product 4', 'Description for product 4, a high-quality item for everyday use.', 5);
INSERT INTO product (id, name, description, category_id) VALUES (5,'Product 5', 'Description for product 5, a high-quality item for everyday use.', 1);
INSERT INTO product (id, name, description, category_id) VALUES (6,'Product 6', 'Description for product 6, a high-quality item for everyday use.', 3);
INSERT INTO product (id, name, description, category_id) VALUES (7,'Product 7', 'Description for product 7, a high-quality item for everyday use.', 2);
INSERT INTO product (id, name, description, category_id) VALUES (8,'Product 8', 'Description for product 8, a high-quality item for everyday use.', 2);
INSERT INTO product (id, name, description, category_id) VALUES (9,'Product 9', 'Description for product 9, a high-quality item for everyday use.', 1);
INSERT INTO product (id, name, description, category_id) VALUES (10,'Product 10', 'Description for product 10, a high-quality item for everyday use.', 3);
INSERT INTO product (id, name, description, category_id) VALUES (11,'Product 11', 'Description for product 11, a high-quality item for everyday use.', 2);
INSERT INTO product (id, name, description, category_id) VALUES (12,'Product 12', 'Description for product 12, a high-quality item for everyday use.', 3);
INSERT INTO product (id, name, description, category_id) VALUES (13,'Product 13', 'Description for product 13, a high-quality item for everyday use.', 1);
INSERT INTO product (id, name, description, category_id) VALUES (14,'Product 14', 'Description for product 14, a high-quality item for everyday use.', 4);
INSERT INTO product (id, name, description, category_id) VALUES (15,'Product 15', 'Description for product 15, a high-quality item for everyday use.', 1);
INSERT INTO product (id, name, description, category_id) VALUES (16,'Product 16', 'Description for product 16, a high-quality item for everyday use.', 1);
INSERT INTO product (id, name, description, category_id) VALUES (17,'Product 17', 'Description for product 17, a high-quality item for everyday use.', 1);
INSERT INTO product (id, name, description, category_id) VALUES (18,'Product 18', 'Description for product 18, a high-quality item for everyday use.', 2);
INSERT INTO product (id, name, description, category_id) VALUES (19,'Product 19', 'Description for product 19, a high-quality item for everyday use.', 5);
INSERT INTO product (id, name, description, category_id) VALUES (20,'Product 20', 'Description for product 20, a high-quality item for everyday use.', 2);
INSERT INTO product (id, name, description, category_id) VALUES (21,'Product 21', 'Description for product 21, a high-quality item for everyday use.', 1);
INSERT INTO product (id, name, description, category_id) VALUES (22,'Product 22', 'Description for product 22, a high-quality item for everyday use.', 5);
INSERT INTO product (id, name, description, category_id) VALUES (23,'Product 23', 'Description for product 23, a high-quality item for everyday use.', 3);
INSERT INTO product (id, name, description, category_id) VALUES (24,'Product 24', 'Description for product 24, a high-quality item for everyday use.', 4);
INSERT INTO product (id, name, description, category_id) VALUES (25,'Product 25', 'Description for product 25, a high-quality item for everyday use.', 2);
INSERT INTO product (id, name, description, category_id) VALUES (26,'Product 26', 'Description for product 26, a high-quality item for everyday use.', 5);
INSERT INTO product (id, name, description, category_id) VALUES (27,'Product 27', 'Description for product 27, a high-quality item for everyday use.', 4);
INSERT INTO product (id, name, description, category_id) VALUES (28,'Product 28', 'Description for product 28, a high-quality item for everyday use.', 3);
INSERT INTO product (id, name, description, category_id) VALUES (29,'Product 29', 'Description for product 29, a high-quality item for everyday use.', 4);
INSERT INTO product (id, name, description, category_id) VALUES (30,'Product 30', 'Description for product 30, a high-quality item for everyday use.', 5);
INSERT INTO product (id, name, description, category_id) VALUES (31,'Product 31', 'Description for product 31, a high-quality item for everyday use.', 1);
INSERT INTO product (id, name, description, category_id) VALUES (32,'Product 32', 'Description for product 32, a high-quality item for everyday use.', 2);
INSERT INTO product (id, name, description, category_id) VALUES (33,'Product 33', 'Description for product 33, a high-quality item for everyday use.', 4);
INSERT INTO product (id, name, description, category_id) VALUES (34,'Product 34', 'Description for product 34, a high-quality item for everyday use.', 4);
INSERT INTO product (id, name, description, category_id) VALUES (35,'Product 35', 'Description for product 35, a high-quality item for everyday use.', 2);
INSERT INTO product (id, name, description, category_id) VALUES (36,'Product 36', 'Description for product 36, a high-quality item for everyday use.', 3);
INSERT INTO product (id, name, description, category_id) VALUES (37,'Product 37', 'Description for product 37, a high-quality item for everyday use.', 1);
INSERT INTO product (id, name, description, category_id) VALUES (38,'Product 38', 'Description for product 38, a high-quality item for everyday use.', 4);
INSERT INTO product (id, name, description, category_id) VALUES (39,'Product 39', 'Description for product 39, a high-quality item for everyday use.', 3);
INSERT INTO product (id, name, description, category_id) VALUES (40,'Product 40', 'Description for product 40, a high-quality item for everyday use.', 4);
INSERT INTO product (id, name, description, category_id) VALUES (41,'Product 41', 'Description for product 41, a high-quality item for everyday use.', 2);
INSERT INTO product (id, name, description, category_id) VALUES (42,'Product 42', 'Description for product 42, a high-quality item for everyday use.', 3);
INSERT INTO product (id, name, description, category_id) VALUES (43,'Product 43', 'Description for product 43, a high-quality item for everyday use.', 1);
INSERT INTO product (id, name, description, category_id) VALUES (44,'Product 44', 'Description for product 44, a high-quality item for everyday use.', 3);
INSERT INTO product (id, name, description, category_id) VALUES (45,'Product 45', 'Description for product 45, a high-quality item for everyday use.', 1);
INSERT INTO product (id, name, description, category_id) VALUES (46,'Product 46', 'Description for product 46, a high-quality item for everyday use.', 4);
INSERT INTO product (id, name, description, category_id) VALUES (47,'Product 47', 'Description for product 47, a high-quality item for everyday use.', 1);
INSERT INTO product (id, name, description, category_id) VALUES (48,'Product 48', 'Description for product 48, a high-quality item for everyday use.', 3);
INSERT INTO product (id, name, description, category_id) VALUES (49,'Product 49', 'Description for product 49, a high-quality item for everyday use.', 3);
INSERT INTO product (id, name, description, category_id) VALUES (50,'Product 50', 'Description for product 50, a high-quality item for everyday use.', 1);
INSERT INTO product (id, name, description, category_id) VALUES (51,'Product 51', 'Description for product 51, a high-quality item for everyday use.', 5);
INSERT INTO product (id, name, description, category_id) VALUES (52,'Product 52', 'Description for product 52, a high-quality item for everyday use.', 1);
INSERT INTO product (id, name, description, category_id) VALUES (53,'Product 53', 'Description for product 53, a high-quality item for everyday use.', 2);
INSERT INTO product (id, name, description, category_id) VALUES (54,'Product 54', 'Description for product 54, a high-quality item for everyday use.', 3);
INSERT INTO product (id, name, description, category_id) VALUES (55,'Product 55', 'Description for product 55, a high-quality item for everyday use.', 1);
INSERT INTO product (id, name, description, category_id) VALUES (56,'Product 56', 'Description for product 56, a high-quality item for everyday use.', 2);
INSERT INTO product (id, name, description, category_id) VALUES (57,'Product 57', 'Description for product 57, a high-quality item for everyday use.', 3);
INSERT INTO product (id, name, description, category_id) VALUES (58,'Product 58', 'Description for product 58, a high-quality item for everyday use.', 4);
INSERT INTO product (id, name, description, category_id) VALUES (59,'Product 59', 'Description for product 59, a high-quality item for everyday use.', 5);
INSERT INTO product (id, name, description, category_id) VALUES (60,'Product 60', 'Description for product 60, a high-quality item for everyday use.', 1);
INSERT INTO product (id, name, description, category_id) VALUES (61,'Product 61', 'Description for product 61, a high-quality item for everyday use.', 2);
INSERT INTO product (id, name, description, category_id) VALUES (62,'Product 62', 'Description for product 62, a high-quality item for everyday use.', 3);
INSERT INTO product (id, name, description, category_id) VALUES (63,'Product 63', 'Description for product 63, a high-quality item for everyday use.', 4);
INSERT INTO product (id, name, description, category_id) VALUES (64,'Product 64', 'Description for product 64, a high-quality item for everyday use.', 5);
INSERT INTO product (id, name, description, category_id) VALUES (65,'Product 65', 'Description for product 65, a high-quality item for everyday use.', 1);
INSERT INTO product (id, name, description, category_id) VALUES (66,'Product 66', 'Description for product 66, a high-quality item for everyday use.', 2);
INSERT INTO product (id, name, description, category_id) VALUES (67,'Product 67', 'Description for product 67, a high-quality item for everyday use.', 3);
INSERT INTO product (id, name, description, category_id) VALUES (68,'Product 68', 'Description for product 68, a high-quality item for everyday use.', 4);
INSERT INTO product (id, name, description, category_id) VALUES (69,'Product 69', 'Description for product 69, a high-quality item for everyday use.', 5);
INSERT INTO product (id, name, description, category_id) VALUES (70,'Product 70', 'Description for product 70, a high-quality item for everyday use.', 1);